### ISSUE TITLE
java.lang.IllegalStateException: You need to use a Theme.AppCompat theme 

### ISSUE THREAD

**Issue by chanwoong528** [react-native-seoul/react-native-naver-login#124]
### Version of naver-login libraries

가장 최신 
### Version of react-native

rn : 0.68.2
### Platforms you faced the error (IOS or Android or both?)

Android only
### Actual behavior

네이버 로그인 첫 시도는 성공하며 잘 동작 합니다. 
한데 로그아웃을 했다가
다시 로그인을 시도를 하면 아래와 같은 에러가 발생하면서 앱이 crash 됩니다. 
````
  java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
        at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:846)
        at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:809)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:696)
        at androidx.appcompat.app.AppCompatDialog.setContentView(AppCompatDialog.java:95)
        at com.navercorp.nid.progress.NidProgressDialog.init(NidProgressDialog.kt:39)
        at com.navercorp.nid.progress.NidProgressDialog.<init>(NidProgressDialog.kt:32)
        at com.navercorp.nid.oauth.NidOAuthLogin.refreshToken(NidOAuthLogin.kt:198)
        at com.navercorp.nid.NaverIdLoginSDK.authenticate(NaverIdLoginSDK.kt:113)
        at com.dooboolab.naverlogin.RNNaverLoginModule$1.run(RNNaverLoginModule.java:131)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7842)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```
`

### Tested environment (Emulator? Real Device?)
Emulator pixel 2
<!-- 오류를 겪고 있는 개발환경(에뮬레이터 또는 실제 기기)을 적어주세요 -->

**Comment by seongwan-inno** [comment]
동일한 문제를 가지고 있는데 해결방안을 못찾겠네요.. 임시라도 처리해야하는데 흠.

**Comment by sonson1023** [comment]
어떻게 임시방편으로 처리할수 있을까요 흠..

**Comment by jungseungjin** [comment]
어제부터 하루종일 해보는데 아직 방법을 못찾았네요...

**Comment by 92kimyoungchan** [comment]
저도 방법을 못찾고있네요... 로그아웃하고 다시 로그인하면 바로 죽으니
그런데 액티비티의 값이 null 인게 죽는 이유가 맞는거같아요
안드로이드 네이티브 지식 있으신분은 해결가능하실거같네요

**Comment by appltree** [comment]
로그아웃할때 NaverLogin.logout() 호출 하시면 되던데요.

**Comment by appltree** [comment]
로그아웃할때 NaverLogin.logout() 호출 하면 되던데요.

**Comment by appltree** [comment]
./node_modules/@react-native-seoul/naver-login/android/src/main/java/com/dooboolab/naverlogin/RNNaverLoginModule.java


```
          naverIdLoginSDK.logout(); <-- 추가
          naverIdLoginSDK.authenticate(reactContext, oAuthLoginCallback);
```

**Comment by chanwoong528** [comment]
@appltree  님의 코드로 할 시 naverIdLoginSDK.logout(); 을 하면 정상 작동 합니다.
감사합니다 @appltree 님
