### ISSUE TITLE
App creash(2.2.0)

### ISSUE THREAD

**Issue by mk0116** [react-native-seoul/react-native-naver-login#133]
로그인 -> 로그아웃 -> 다시 로드인시 크래쉬가 납니다.

2022-06-27 17:09:00.768 17857-17857/co.aienglish E/AndroidRuntime: FATAL EXCEPTION: main
    Process: co.aienglish, PID: 17857
    java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
        at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:846)
        at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:809)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:696)
        at androidx.appcompat.app.AppCompatDialog.setContentView(AppCompatDialog.java:95)
        at com.navercorp.nid.progress.NidProgressDialog.init(NidProgressDialog.kt:39)
        at com.navercorp.nid.progress.NidProgressDialog.<init>(NidProgressDialog.kt:32)
        at com.navercorp.nid.oauth.NidOAuthLogin.refreshToken(NidOAuthLogin.kt:198)
        at com.navercorp.nid.NaverIdLoginSDK.authenticate(NaverIdLoginSDK.kt:113)
        at com.dooboolab.naverlogin.RNNaverLoginModule$1.run(RNNaverLoginModule.java:131)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7850)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

**Comment by GeunwonChoi** [comment]
안녕하세요.

해결된 이슈일까요?

**Comment by mk0116** [comment]
2.3.0버전으로 업그레이드 후 해결되었습니다.
